### ISSUE TITLE
not install

### ISSUE THREAD

**Issue by foXaCe** [lbschenkel/hass-addon-broadlink-bridge#1]
hello, on my odroid xu4 this addon do not install

http://192.168.1.39:8123/frontend_latest/app.29857aca.js:2:87555 Uncaught SecurityError: Blocked a frame with origin "http://192.168.1.39:8123" from accessing a cross-origin frame.

**Comment by lbschenkel** [comment]
Can you please specify the exact steps you're performing, and include logs and/or screenshots?

**Comment by foXaCe** [comment]
19-10-03 14:43:32 ERROR (SyncWorker_34) [hassio.docker.addon] Can't build c523f6d3/armv7-addon-broadlink_bridge:0.1.2.3: The command '/bin/ash -o pipefail -c apk add git gcc musl-dev libffi-dev openssl-dev' returned a non-zero code: 5
19-10-03 14:43:32 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<AddonManager.install() done, defined at /usr/src/hassio/hassio/addons/__init__.py:106> exception=AddonsError()>

**Comment by lbschenkel** [comment]
The building of the Docker image for the add-on is failing at your machine, more specifically at the point in time that some required packages are installed (`apk add git gcc musl-dev libffi-dev openssl-dev`). Because there is no other detail present in the log, I can't really know what went wrong (problem downloading?).

**Comment by lbschenkel** [comment]
Closing due to lack of response from submitter.
